# Generated by Django 2.2.5 on 2019-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_type', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
