# Generated by Django 2.2.5 on 2019-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_cookie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='nut_free',
            field=models.BooleanField(default=True),
        ),
    ]
